FROM node:22-alpine AS buildstep

# ARG BACKEND_API_BASE_URL
# ENV BACKEND_API_BASE_URL=$BACKEND_API_BASE_URL

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .


## step2
FROM nginx:stable-alpine

COPY --from=buildstep app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD [ "nginx","-g","daemon off;" ]