name: Build image and deploy to ECS on AWS
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - '.github/workflows/*'
  workflow_dispatch:

env:
  BACKEND_IMAGE_NAME: ecs-demo-backend
  FRONTEND_IMAGE_NAME: ecs-demo-frontend
jobs:
  Build-image-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repo
        uses: actions/checkout@v4
      - name: Details image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{vars.DOCKERHUB_USERNAME}}/${{env.BACKEND_IMAGE_NAME}}
          tags: |
            latest
            v1.0.${{github.run_number}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  Build-image-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repo
        uses: actions/checkout@v4
      - name: Setup Node and install depencencies
        uses: ./.github/actions/setupnode
        with: 
          node-version: 22
      - name: Build project
        run: npm run build
        working-directory: ./frontend
      - name: Upload dist artifact
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          name: app-build
          path: build/       
      - name: Details image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{vars.DOCKERHUB_USERNAME}}/${{env.FRONTEND_IMAGE_NAME}}
          tags: |
            latest
            v1.0.${{github.run_number}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}